import { DataType } from 'sequelize-typescript';

export const userProperties = [
  {
    name: 'id',
    type: DataType.INTEGER,
    simple_type: 'number',
    unique: true,
    autoIncrement: true,
    primaryKey: true,
    description: 'Unique identifier',
    example: '1',
    exclude_dto: true,
  },
  {
    name: 'email',
    type: DataType.STRING,
    simple_type: 'string',
    unique: true,
    allowNull: true,
    IsEmail: true,
    description: 'Unique email, (optional if the phone number filled)',
    example: 'xxxxxxxx@xxx.com',
    readolny: true,
    validate: true,
  },
  {
    name: 'phoneNumber',
    type: DataType.STRING,
    simple_type: 'string',
    unique: true,
    allowNull: true,
    IsPhoneNumber: true,
    description: 'Unique phone number (optional if email filled)',
    example: '+380671111111',
    validate: true,
  },
  {
    name: 'password',
    type: DataType.STRING,
    simple_type: 'string',
    allowNull: true,
    description: 'Unique password, length for 4 to 16',
    example: 'xxxxxxxxxxxx',
    readolny: true,
    validate: true,
    IsString_: true,
    Length: { min: 4, max: 16 },
  },
  {
    name: 'newPassword',
    type: DataType.STRING,
    simple_type: 'string',
    allowNull: true,
    description: 'Unique password, length for 4 to 16',
    example: 'xxxxxxxxxxxx',
    validate: true,
    IsString_: true,
    Length: { min: 4, max: 16 },
  },
  {
    name: 'activated',
    type: DataType.BOOLEAN,
    simple_type: 'boolean',
    defaultValue: false,
    description: 'Activated user or not',
    example: 'true',
  },
  {
    name: 'verificationCode',
    type: DataType.STRING,
    simple_type: 'string',
    allowNull: true,
    description: 'Verification code',
    example: 'XXXXXX',
  },
  {
    name: 'createdAt',
    type: DataType.DATE,
    simple_type: 'string',
    allowNull: true,
    description: 'Created at',
    example: '01/02/2023 15:15:22',
  },
  {
    name: 'updatedAt',
    type: DataType.DATE,
    simple_type: 'string',
    allowNull: true,
    description: 'Updated at',
    example: '01/02/2023 15:15:22',
  },
];
